env:
  browser: true
  commonjs: true
  es2021: true
extends: google
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  linebreak-style: 0,
  max-len: [2, 120, 4],
  indent: ["error", 4],
  require-jsdoc: 0,
}
